In [ ]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

In [ ]:
# Function to extract Product Title
def get_title(soup):
  title = soup.find('h1',attrs={'class':"ftwN m0 p0 c3 fs20 pt0 p12 pb2 bs ttC"}).text.strip()
  return title
# Function to extract Product Price
def get_price(soup):
  price = soup.find('span',attrs={'class':"dTc vM fs18 cP"}).text.strip(':')
  return price
# Function to extract occasion
def get_type(soup):
  occasion = soup.find('div',attrs={'class':"dIb vT c3"}).text.strip()
  return occasion

In [ ]:
# add your user agent 
HEADERS =({'Use-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36','Accept-Language': 'en-US, en;q=0.5'})

# The webpage URL
URL = "https://www.limeroad.com/clothing/ethnic-wear/kurta-kurtis?src_id=navdeskKurtaKurtis__000"

# HTTP Request
webpage = requests.get(URL, headers=HEADERS)

# Soup Object containing all data
soup = BeautifulSoup(webpage.content, "html.parser")

# Fetch links as List of Tag Objects
links = soup.find_all("a",attrs={"data-pgn":"Prod VIP"})


# Store the links
links_list = []

# Loop for extracting links from Tag Objects
for link in links:
    links_list.append(link.get('href'))

d = {"title":[], "price":[], "type":[], "link":[]}
    
# Loop for extracting product details from each link 
for link in links_list:
    new_webpage = requests.get("https://www.limeroad.com" + link, headers=HEADERS)
    new_soup = BeautifulSoup(new_webpage.content, "html.parser")
    d['title'].append(get_title(new_soup))
    d['price'].append(get_price(new_soup))
    d['type'].append(get_type(new_soup))
    d['link'].append("https://www.limeroad.com" + link)

    
limeroad_df = pd.DataFrame.from_dict(d)
limeroad_df['title'].replace('', np.nan, inplace=True)
limeroad_df = limeroad_df.dropna(subset=['title'])
limeroad_df.to_csv("limeroad_data.csv", header=True, index=False)

In [ ]:
limeroad_df

,title,price,type,link
0,chevron print a-line kurta,₹ 899,Casual Wear,https://www.limeroad.com/blue-cotton-svarchi-f...
1,printed rayon flared kurta,₹ 999,Casual Wear,https://www.limeroad.com/multi-rayon-tissu-p19...
2,cream printed anarkali kurta,₹ 1449,Festive Wear,https://www.limeroad.com/cream-cotton-divena-p...
3,black floral straight kurta,₹ 999,Casual Wear,https://www.limeroad.com/black-cotton-piroh-p1...
4,lahriya print straight kurta,₹ 749,Casual Wear,https://www.limeroad.com/orange-cotton-jc4u-p1...
5,floral printed flared kurta,₹ 949,Casual Wear,https://www.limeroad.com/green-rayon-tissu-p16...
6,round neck printed a-line kurta,₹ 799,Casual Wear,https://www.limeroad.com/green-cotton-trillmix...
7,floral straight kurti,₹ 649,Casual Wear,https://www.limeroad.com/blue-rayon-tissu-p183...